# Generated by Django 2.2.7 on 2019-11-07 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expence',
            name='text',
            field=models.CharField(max_length=50),
        ),
    ]
